export const ACTIVITIES_CLIENT = 'ACTIVITIES';
export const CUSTOMERS_CLIENT = 'CUSTOMERS';
export const REPORTS_CLIENT = 'REPORTS';

export const ACTIVITIES_SERVICE = 'ACTIVITIES_SERVICE';
export const CUSTOMERS_SERVICE = 'CUSTOMERS_SERVICE';
export const REPORTS_SERVICE = 'REPORTS_SERVICE';
